### ISSUE TITLE
Syntax highlighting showing in blocks

### ISSUE THREAD

**Issue by nicolasjulioflores** [kyoz/purify#1]
Hey kyoz, 

I'm currently using your purify theme and am having a little trouble getting it to render properly:
![Screen Shot 2019-10-02 at 5 55 10 PM](https://user-images.githubusercontent.com/31143150/66084994-fe13ff80-e53d-11e9-9915-1e695eb4eb91.png)

I know the problem is likely on my end because I am able to get it to render properly when I ssh into another machine. 

The machine that it currently doesn't work on:
* macOS Mojave 10.14.1
* Vim 8.1

Machine that it does work on:
* Fedora 30
* Vim 8.1

The vimrc file is the same on both

Probably a super noob vim question but yours is definitely been the best theme I've used so far and so I really want to get it work on my machine!

**Comment by kyoz** [comment]
Thanks @nicolasjulioflores for using purify :heart:. I think this problem is because the italic support of the font. I  used to have this problem in the past too. Vim will highlight italic text if the font doesn't support italic well.

Can you please try another fonts like [iosevka](https://github.com/be5invis/Iosevka) or [firacode](https://github.com/tonsky/FiraCode)

Or else, try to disable purify's italic support with:

```viml
let g:purify_italic = 0
```
You can find more infomation, configurations [here](https://github.com/kyoz/purify/tree/master/vim)

Please let me know if it work :cat:

**Comment by pnor** [comment]
Hey, 

I was having the same problem, but after adding
```let g:purify_italic = 0```
to my ~/.vimrc, and running `:!source ~/.vimrc` in a file, it resolves

Before:
<img width="1680" alt="Screen Shot 2019-10-10 at 11 09 09 AM" src="https://user-images.githubusercontent.com/19177346/66581792-b8af8d80-eb4e-11e9-916a-d292cb9d07a9.png">

After running :!source ~/.vimrc in file:
<img width="1680" alt="Screen Shot 2019-10-10 at 11 09 28 AM" src="https://user-images.githubusercontent.com/19177346/66581817-c238f580-eb4e-11e9-8142-14db1bd5756f.png">

I have yet to figure out how to do this without the extra command on startup though

**Comment by kyoz** [comment]
Hi @pnor , as i answer @nicolasjulioflores . This is because of the font italic support.

In default, purify support italic, bold...out of the box. If you haven't install italic version of your currently using font. Vim will try convert it to block (This is similar to all other theme, except they don't support italic)

To solve this, can you try install italic version of the font you are using.

I'm using iosevka font and i'v install Regular and Italic version.

Let me know if it work, thank you :heart:

**Comment by pnor** [comment]
I fixed it, thanks
I should of put let `g:purify_italic = 0` before `colo purify`

**Comment by kyoz** [comment]
yay. but the italic support is quite cool. can you give it a try by install italic version of the font you are using. if so, you dont have to set that config and have italic support.

**Comment by pnor** [comment]
I have got italics to work; after making sure my terminal render italics and adding the italic support of the font I added 
```
let &t_ZH="\e[3m"
let &t_ZR="\e[23m"
```
to the vimrc.

<img width="1680" alt="Screen Shot 2019-10-11 at 8 57 53 PM" src="https://user-images.githubusercontent.com/19177346/66692213-2dc3b580-ec6a-11e9-99ee-55dd7850bf51.png">


Thank you for the help and the color scheme!

**Comment by kyoz** [comment]
Yay, thank you for using purify. So i'll closing this issue. If you have any problem, please open a new issue :heart:
