### ISSUE TITLE
GVIM White Background Issue

### ISSUE THREAD

**Issue by PurpleHobo** [kyoz/purify#10]
I saw the closed thread where someone had the same issue as me, but it was closed without the problem being fixed. Ill check up on this late tomorrow AEST as I'm busy. 

Notable info: I used vim-plug to install and it works fine with vim in a terminal. I only use it for node and the example is some js.
Only notable vimrc lines:
autocmd BufEnter *.js colorscheme purify
Plug 'kyoz/purify', { 'rtp': 'vim' }

![image](https://user-images.githubusercontent.com/64588827/105144050-65492f00-5b48-11eb-9d01-c434e2798248.png)

**Comment by PurpleHobo** [comment]
:set background=dark also does nothing

**Comment by kyoz** [comment]
Hi @PurpleHobo , sorry for lately response, didn't receive notify from github. I'll check it out, i think there need some config for `.gvimrc ` :smile:

**Comment by kyoz** [comment]
Hi @PurpleHobo . I just take a look into this issue and remember that by default, i didn't set background color for Purify. It'll take your terminal background color to display. This is because vim's colors in terminal is pretty limit.

But for gvim and nvim-qt. I'v add a patch which will set default background. Like below.

![image](https://user-images.githubusercontent.com/29815830/106252767-2fdbca00-6249-11eb-9802-9c5324a3d051.png)

Please update Purify with `PlugUpdate` and let me know if it work :smile:

**Comment by PurpleHobo** [comment]
Ill have a look now

**Comment by PurpleHobo** [comment]
Works perfectly man, cheers!
